---
openapi: "3.0.1"
info:
  title: "Standing Requests"
  description: "This API specification describes the data structures used in the requests\
    \ and responses relating to standing requests.\n\n`It allows the consumer of the\
    \ API to view the standing requests in ETMP.`\n\nThe consumer of this API will\
    \ be able to view the information by providing regime, tax payer ID type and tax\
    \ payer ID value. The API will then respond with the corresponding details of\
    \ standing requests or an appropriate error message.\n\n ```The interface is implemented\
    \ as a synchronous REST service.```\n```\nChange Log\n  ```\n | Version | Date\
    \ | Author| Description ||\n
    |---|----|------|-----|-----|\n
    |0.1.0 | 24-01-2025| Pradeep Nair| Initial draft (EPID1570 v0.1)\n
    |0.2.0 | 30-01-2025 | Pradeep Nair| Updated API name, description, response structure, error codes, sample responses\n
    |0.2.1 | 06-02-2025 | Pradeep Nair| Removed organisation example, updated sample response with realistic values\n"
  version: "0.2.1"
  termsOfService: "http://INSERT_LINK_TO_SLA_HERE"
  contact:
    name: "SAP ETMP Integration Services"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  x-integration-catalogue:
    reviewed-date: "2024-09-20T12:00:00Z"
    platform: "HIP"
    publisher-reference: "EPID1570"
    short-description: "API to view ETMP Standing Requests"
    status: "ALPHA"
    api-type: "SIMPLE"
    backends: "ETMP"
    domain: 2
    sub-domain: 2.17
servers:
  - url: "http://etmp-egress-gateway.egress.svc.cluster.local"
    description: "Egress Gateway to ETMP"
tags:
  - name: "cross-regime"
    description: "Applicable to all HMRC Regimes"
paths:
  /RESTAdapter/{regime}/standing-requests/{taxpayerIdType}/{taxpayerIdValue}:
    get:
      deprecated: false
      summary: "Consumer to ETMP Standing Requests Display Operation"
      description: "This is an operation that will allow synchronous display of standing\
        \ requests for a consumer (e.g.MDTP).\n\nOnce the message is processed in\
        \ ETMP the API will respond with either the corresponding details or an appropriate\
        \ error message.\n\n`EPID reference: EPID1570`"
      operationId: "StandingRequestsGET"
      tags:
        - "cross-regime"
      parameters:
        - name: "correlationid"
          in: "header"
          description: "Unique Alphanumeric Acknowledgement Reference number used for\
          \ correlation purposes. Must be generated by the originating system. Must\
          \ conform to 36-character UUID (unformatted)."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
            example: "f0bd1f32-de51-15cc-9b18-0520d6e3ab1a"
        - name: "regime"
          in: "path"
          description: "Regime"
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            minLength: 1
            maxLength: 4
            example: "VATC"
        - name: "taxpayerIdType"
          in: "path"
          description: "Tax Payer ID Type"
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            minLength: 1
            maxLength: 20
            example: "VRN"
        - name: "taxpayerIdValue"
          in: "path"
          description: "Tax Payer ID Value"
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            minLength: 1
            maxLength: 60
            example: "123456789"
        - name: "X-Originating-System"
          in: "header"
          description: "System that is the originator of the message. When the consumer\
          \ is Digital, value 'MDTP' required."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            minLength: 1
            maxLength: 30
            example: "MDTP"
        - name: "X-Receipt-Date"
          in: "header"
          description: "The time the message was created by the system sending the message.\
          \ The value should follow this date-time pattern, and be represented in\
          \ the UTC time zone: yyyy-MM-ddTHH:mm:ssZ."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            format: "date-time"
            example: "2024-09-25T12:05:45Z"
        - name: "X-Transmitting-System"
          in: "header"
          description: "Intermediary system that performs the transmission of the message.\
          \ Fixed value of 'HIP' required."
          required: true
          deprecated: false
          allowEmptyValue: false
          style: "simple"
          schema:
            type: "string"
            enum:
              - "HIP"
            example: "HIP"
      responses:
        "200":
          description: "Successful Display Operation"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchemaSuccess"
              examples:
                Successful Display Operation:
                  value:
                    processingDate: "2025-02-05T09:30:47Z"
                    standingRequests:
                      - requestNumber: "20000037272"
                        requestCategory: "3"
                        createdOn: "2023-11-30"
                        changedOn: "2024-12-26"
                        requestItems:
                          - period: "1"
                            periodKey: "24A1"
                            startDate: "2024-02-01"
                            endDate: "2024-04-30"
                            dueDate: "2024-03-31"
                            amount: 22945.23
                            chargeReference: "XD006411191344"
                            postingDueDate: "2024-03-31"
                          - period: "2"
                            periodKey: "23A1"
                            startDate: "2024-02-01"
                            endDate: "2024-04-30"
                            dueDate: "2024-04-30"
                            amount: 22945.23
                            chargeReference: "XD006411191345"
                            postingDueDate: "2024-04-30"
                          - period: "3"
                            periodKey: "23A2"
                            startDate: "2024-05-01"
                            endDate: "2024-06-30"
                            dueDate: "2024-06-30"
                            amount: 22945.23
                            chargeReference: "XD006411191346"
                            postingDueDate: "2024-06-30"
                          - period: "4"
                            periodKey: "24A2"
                            startDate: "2024-05-01"
                            endDate: "2024-07-31"
                            dueDate: "2024-07-31"
                            amount: 22945.23
                            chargeReference: "XD006411191347"
                            postingDueDate: "2024-07-31"
                          - period: "5"
                            periodKey: "24A3"
                            startDate: "2024-08-01"
                            endDate: "2024-10-31"
                            dueDate: "2024-09-30"
                            amount: 22945.23
                            chargeReference: "XD006411191348"
                            postingDueDate: "2024-09-30"
                          - period: "6"
                            periodKey: "24A3"
                            startDate: "2024-08-01"
                            endDate: "2024-10-31"
                            dueDate: "2024-10-31"
                            amount: 22945.23
                            chargeReference: "XD006411191349"
                            postingDueDate: "2024-10-31"
                          - period: "7"
                            periodKey: "24A4"
                            startDate: "2024-11-01"
                            endDate: "2025-01-31"
                            dueDate: "2024-12-31"
                            amount: 22945.23
                            chargeReference: "XD006411191350"
                            postingDueDate: "2024-10-31"
                          - period: "8"
                            periodKey: "24A4"
                            startDate: "2024-11-01"
                            endDate: "2025-01-31"
                            dueDate: "2025-01-31"
                            amount: 22945.23
                            chargeReference: "XD006411191351"
                            postingDueDate: "2025-01-31"
                      - requestNumber: "20000037277"
                        requestCategory: "3"
                        createdOn: "2024-11-30"
                        changedOn: "2025-01-26"
                        requestItems:
                          - period: "1"
                            periodKey: "25A1"
                            startDate: "2025-02-01"
                            endDate: "2025-04-30"
                            dueDate: "2025-03-31"
                            amount: 122945.23
                          - period: "2"
                            periodKey: "25A1"
                            startDate: "2025-02-01"
                            endDate: "2025-04-30"
                            dueDate: "2025-04-30"
                            amount: 122945.23
                          - period: "3"
                            periodKey: "25A2"
                            startDate: "2025-05-01"
                            endDate: "2025-06-30"
                            dueDate: "2025-06-30"
                            amount: 122945.23
                          - period: "4"
                            periodKey: "25A2"
                            startDate: "2025-05-01"
                            endDate: "2025-07-31"
                            dueDate: "2025-07-31"
                            amount: 122945.23
                          - period: "5"
                            periodKey: "25A3"
                            startDate: "2025-08-01"
                            endDate: "2025-10-31"
                            dueDate: "2025-09-30"
                            amount: 122945.23
                          - period: "6"
                            periodKey: "25A3"
                            startDate: "2025-08-01"
                            endDate: "2025-10-31"
                            dueDate: "2025-10-31"
                            amount: 122945.23
                          - period: "7"
                            periodKey: "25A4"
                            startDate: "2025-11-01"
                            endDate: "2025-01-31"
                            dueDate: "2025-12-31"
                            amount: 122945.23
                          - period: "8"
                            periodKey: "25A4"
                            startDate: "2025-11-01"
                            endDate: "2026-01-31"
                            dueDate: "2026-01-31"
                            amount: 122945.23
        "400":
          description: "Bad Request"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchemaAllErrorTypes"
              examples:
                Bad Request:
                  value:
                    error:
                      code: "400"
                      message: "Invalid&#x20;JSON&#x20;message&#x20;content&#x20;used&#x3b;&#x20;Message&#x3a;&#x20;&quot;Expected&#x20;a&#x20;&#x27;,&#x27;&#x20;or&#x20;&#x27;&#x7d;&#x27;&#x20;at&#x20;character&#x20;93&#x20;of&#x20;&#x7b;&#xa;&#x9;&quot;idType&quot;&#x3a;&#x20;&quot;EMPREF&quot;,&#xa;&#x9;&quot;idValue&quot;&#x3a;&#x20;&quot;864FZ00049&quot;,&#xa;&#x9;&quot;regimeType&quot;&#x3a;&#x20;&quot;PAYE&quot;,&#xa;&#x9;&quot;lockReason&quot;&#x3a;&#x20;&quot;8&quot;&#xa;&#x9;&quot;chargeReferences&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;XM123456789812&quot;,&#xa;&#x9;&#x9;&quot;XM123456781234&quot;,&#xa;&#x9;&#x9;&quot;XC123111781234&quot;&#xa;&#x9;&#x5d;,&#x9;&#xa;&#x9;&quot;createNote&quot;&#x3a;&#x20;true,&#xa;&#x9;&quot;noteType&quot;&#x3a;&#x20;&quot;TTP&quot;,&#xa;&#x9;&quot;noteLines&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;paymentPlanType&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;TTP&quot;,&#xa;&#x9;&#x9;&quot;arrangementAgreedDate&#x3a;&#x20;2022-02-01&quot;,&#xa;&#x9;&#x9;&quot;arrangementChannel&#x3a;&#x20;&#x20;&#x20;&#x20;ePAYE&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentAmount&#x3a;&#x20;&#x20;&#x20;&#x20;1234.56&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentDate&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;2022-03-01&quot;,&#xa;&#x9;&#x9;&quot;regularPaymentAmount&#x3a;&#x20;&#x20;1000&quot;,&#xa;&#x9;&#x9;&quot;paymentFrequency&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;Monthly&quot;,&#xa;&#x9;&#x9;&quot;arrangementReviewDate&#x3a;&#x20;2022-11-02&quot;,&#xa;&#x9;&#x9;&quot;ddiReference&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;123456789012&quot;&#xa;&#x9;&#x5d;&#xa;&#x7d;&quot;"
                      logID: "C0000AB8190C86300000000200006836"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "415":
          description: "Unsupported media-type"
        "422":
          description: "Unprocessable  -  ETMP validation errors.Errors of this kind\
            \ indicate that ETMP successfully received the data without any technical\
            \ issues, however it is unable to process the data further for the given\
            \ reason.\n  | Code | Text |\n  |---|----|\n 002|Invalid Tax Regime\n\
            \ 003|Request Could Not Be Processed\n 004|Customer Is Not On A VAT Scheme\n\
            \ 015|Invalid ID Type\n 016|Invalid ID Number"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchemaAllErrorTypes"
              examples:
                Invalid Tax Regime:
                  value:
                    errors:
                      processingDate: "2024-07-15T09:45:17Z"
                      code: "002"
                      text: "Invalid Tax Regime"
        "500":
          description: "Internal Server Error"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationidResponseType"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchemaAllErrorTypes"
              examples:
                Internal Server Error:
                  value:
                    error:
                      code: "500"
                      message: "Error&#x20;while&#x20;sending&#x20;message&#x20;to&#x20;module&#x20;processor&#x3a;&#x20;Sender&#x20;Channel&#x20;&#x27;CCOS_01_REST_Out_eSSTTP_PaymentLock_Set&#x27;&#x20;&#x28;ID&#x3a;&#x20;624ce8b4f8773eb0b227f1a90b6f40a5&#x29;&#x3a;&#x20;Catching&#x20;exception&#x20;calling&#x20;messaging&#x20;system&#x3a;&#x20;com.sap.aii.af.sdk.xi.srt.BubbleException&#x3a;&#x20;System&#x20;Error&#x20;Received.&#x20;HTTP&#x20;Status&#x20;Code&#x20;&#x3d;&#x20;200&#x3a;&#x20;However&#x20;System&#x20;Error&#x20;received&#x20;in&#x20;payload&#x20;ErrorCode&#x20;&#x3d;&#x20;INCORRECT_PAYLOAD_DATA&#x20;ErrorCategory&#x20;&#x3d;&#x20;XIServer&#x20;Parameter1&#x20;&#x3d;&#x20;&#x20;Parameter2&#x20;&#x3d;&#x20;&#x20;Parameter3&#x20;&#x3d;&#x20;&#x20;Parameter4&#x20;&#x3d;&#x20;&#x20;Additional&#x20;text&#x20;&#x3d;&#x20;&#x20;ErrorStack&#x20;&#x3d;&#x20;Error&#x20;while&#x20;processing&#x20;message&#x20;payload&#xa;&#xa;An&#x20;error&#x20;occurred&#x20;when&#x20;deserializing&#x20;in&#x20;the&#x20;simple&#x20;transformation&#x20;program&#x20;&#x2f;1SAI&#x2f;SAS476436EAEE64FB2B9096&#xa;Value&#x20;is&#x20;longer&#x20;than&#x20;the&#x20;maximum&#x20;permitted&#x20;length&#x20;15&#x3a;&#x20;&quot;864FZ077777770049&quot;&#xa;&#x20;&#x5b;http&#x3a;&#x2f;&#x2f;sap.com&#x2f;xi&#x2f;XI&#x2f;Message&#x2f;30&#x5e;Error&#x20;&quot;INCORRECT_PAYLOAD_DATA&quot;&#x5d;"
                      logID: "C0000AB8190C8E1F000000C700006836"
components:
  headers:
    correlationidResponseType:
      description: "Unique alphanumeric number used for correlation purposes. Generated\
        \ by the originating system and included in the response. Conforms to 36-character\
        \ UUID (formatted)."
      style: "simple"
      required: false
      deprecated: false
      schema:
        type: "string"
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
  schemas:
    date_type:
      description: "Date format YYYY-MM-DD"
      type: "string"
      format: "date"
    dateTime_type:
      description: "Datetime format yyyy-mm-ddTHH:MM:SSZ"
      type: "string"
      format: "date-time"
    error_type:
      type: "object"
      properties:
        code:
          type: "string"
          enum:
            - "400"
            - "500"
        message:
          type: "string"
          minLength: 1
          maxLength: 5000
        logID:
          type: "string"
          minLength: 32
          maxLength: 32
          pattern: "^[A-F0-9]{32}$"
      required:
        - "code"
        - "message"
        - "logID"
      additionalProperties: false
    errors_type:
      type: "object"
      properties:
        processingDate:
          type: "string"
          pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
        code:
          type: "string"
          enum:
            - "002"
            - "003"
            - "004"
            - "015"
            - "016"
        text:
          type: "string"
          minLength: 1
          maxLength: 100
      required:
        - "processingDate"
        - "code"
        - "text"
    period_type:
      description: "Period"
      type: "string"
      minLength: 1
      maxLength: 3
    requestNumber_type:
      description: "Request Number"
      type: "string"
      minLength: 1
      maxLength: 12
    ResponseSchemaAllErrorTypes:
      type: "object"
      oneOf:
        - type: "object"
          properties:
            error:
              $ref: "#/components/schemas/error_type"
          additionalProperties: false
        - type: "object"
          properties:
            errors:
              $ref: "#/components/schemas/errors_type"
          additionalProperties: false
    ResponseSchemaSuccess:
      description: "Standing Requests Display API Response v0.1"
      type: "object"
      properties:
        processingDate:
          type: "string"
          description: "Datetime format yyyy-mm-ddTHH:MM:SSZ"
          $ref: "#/components/schemas/dateTime_type"
        standingRequests:
          description: "Standing Requests"
          type: "array"
          minItems: 1
          items:
            type: "object"
            properties:
              requestNumber:
                description: "Request Number"
                $ref: "#/components/schemas/requestNumber_type"
              requestCategory:
                description: "Request Category, possible values: 3 - VAT POA Instalment"
                type: "string"
                minLength: 1
                maxLength: 1
              createdOn:
                description: "Created On"
                $ref: "#/components/schemas/date_type"
              changedOn:
                description: "Changed On"
                $ref: "#/components/schemas/date_type"
              requestItems:
                description: "Request Items contained within the Request Number"
                type: "array"
                minItems: 1
                items:
                  type: "object"
                  properties:
                    period:
                      description: "Period"
                      $ref: "#/components/schemas/period_type"
                    periodKey:
                      description: "Period Key"
                      type: "string"
                      minLength: 4
                      maxLength: 4
                    startDate:
                      description: "Start Date"
                      $ref: "#/components/schemas/date_type"
                    endDate:
                      description: "End Date"
                      $ref: "#/components/schemas/date_type"
                    dueDate:
                      description: "Due Date"
                      $ref: "#/components/schemas/date_type"
                    amount:
                      description: "Amount(11 Digits before Decimal and 2 after decimal)"
                      type: "number"
                      minimum: -9.999999999999E10
                      maximum: 9.999999999999E10
                      multipleOf: 0.01
                    chargeReference:
                      description: "Charge Reference"
                      type: "string"
                      minLength: 1
                      maxLength: 16
                    postingDueDate:
                      description: "Posting Due Date"
                      $ref: "#/components/schemas/date_type"
                  required:
                    - "period"
                    - "periodKey"
                    - "startDate"
                    - "endDate"
                    - "dueDate"
                    - "amount"
                  additionalProperties: false
            required:
              - "requestNumber"
              - "requestCategory"
              - "createdOn"
              - "requestItems"
            additionalProperties: false
      required:
        - "processingDate"
        - "standingRequests"
      additionalProperties: false
